import { Form } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/components/redux-provider";
import "@/assets/styles/components/index.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="flex ">
          <div className="w-[40%]">
            <Form />
          </div>
          <div className="w-[60%]"> */}
        <ReduxProvider>{children}</ReduxProvider>
        {/* </div>
        </div> */}
      </body>
    </html>
  );
}
